/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.amikbdg.tacal.app;
import com.opencsv.CSVReader;
import com.opencsv.CSVReaderBuilder;
import com.opencsv.CSVWriter;
import java.awt.*;
import java.awt.event.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author DELL
 */
class CSV_FILTER extends javax.swing.filechooser.FileFilter {
        @Override
        public boolean accept(File file) {
            // Allow only directories, or files with ".txt" extension
            return file.isDirectory() || file.getAbsolutePath().endsWith(".csv");
        }
        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "Comma Separated Value Files... (*.csv)";
        }
    } 

public class Main extends javax.swing.JFrame {
    
    final DefaultTableModel dtm;
    
    int NA;
    String NAP;
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        dtm = new DefaultTableModel();
        t_nilai.setModel(dtm);
        dtm.addColumn("Nama");
        dtm.addColumn("NPM");
        dtm.addColumn("Tugas");
        dtm.addColumn("UTS");
        dtm.addColumn("UAS");
        dtm.addColumn("Nilai Akhir");
    }
    public String FileName;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CSV_BROWSE = new javax.swing.JFileChooser();
        P_Title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        P_CSV = new javax.swing.JPanel();
        B_BROWSE = new javax.swing.JButton();
        TF_FN = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_nilai = new javax.swing.JTable();
        B_EXPORT = new javax.swing.JButton();
        B_Statistik = new javax.swing.JButton();
        P_CAL = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        B_CAL = new javax.swing.JButton();
        CB_PT = new javax.swing.JComboBox<>();
        CB_PUT = new javax.swing.JComboBox<>();
        CB_PUA = new javax.swing.JComboBox<>();
        P_PROC = new javax.swing.JPanel();
        PG = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        LB_PG = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        BrowseMenu = new javax.swing.JMenuItem();
        ResetMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ExitMenu = new javax.swing.JMenuItem();
        About = new javax.swing.JMenu();
        AboutMenu = new javax.swing.JMenuItem();

        CSV_BROWSE.setDialogTitle("Pilih File .CSV");
        CSV_BROWSE.setFileFilter(new CSV_FILTER());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Pengolah Nilai");
        setName("MainFrame"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplikasi Pengolah Nilai");

        javax.swing.GroupLayout P_TitleLayout = new javax.swing.GroupLayout(P_Title);
        P_Title.setLayout(P_TitleLayout);
        P_TitleLayout.setHorizontalGroup(
            P_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        P_TitleLayout.setVerticalGroup(
            P_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        P_CSV.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        B_BROWSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amikbdg/tacal/res/icons8_csv_24px.png"))); // NOI18N
        B_BROWSE.setText("Browse");
        B_BROWSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BROWSEActionPerformed(evt);
            }
        });

        TF_FN.setText("load file...");

        t_nilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "NPM", "Tugas", "UTS", "UAS", "Nilai Akhir"
            }
        ));
        jScrollPane1.setViewportView(t_nilai);

        B_EXPORT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amikbdg/tacal/res/icons8_export_24px_1.png"))); // NOI18N
        B_EXPORT.setText("Ekspor");

        B_Statistik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amikbdg/tacal/res/icons8_bar_chart_24px_1.png"))); // NOI18N
        B_Statistik.setText("Statistik");

        javax.swing.GroupLayout P_CSVLayout = new javax.swing.GroupLayout(P_CSV);
        P_CSV.setLayout(P_CSVLayout);
        P_CSVLayout.setHorizontalGroup(
            P_CSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_CSVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_CSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_CSVLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(P_CSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_CSVLayout.createSequentialGroup()
                                .addComponent(TF_FN, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B_BROWSE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_CSVLayout.createSequentialGroup()
                                .addComponent(B_Statistik)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B_EXPORT)))))
                .addContainerGap())
        );
        P_CSVLayout.setVerticalGroup(
            P_CSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_CSVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_CSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_BROWSE)
                    .addComponent(TF_FN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P_CSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_EXPORT)
                    .addComponent(B_Statistik))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        P_CAL.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Hitung Nilai Akhir");

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setText("Persentase Tugas");

        jLabel4.setText("Persentase UTS");

        jLabel5.setText("Persentase UAS");

        B_CAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amikbdg/tacal/res/icons8_estimates_24px.png"))); // NOI18N
        B_CAL.setText("Hitung");
        B_CAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CALActionPerformed(evt);
            }
        });

        CB_PT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));

        CB_PUT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));

        CB_PUA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "30", "40", "50", "60", "70", "80", "90", "100" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(CB_PUA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B_CAL))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CB_PT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CB_PUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CB_PT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CB_PUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(B_CAL)
                    .addComponent(CB_PUA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout P_CALLayout = new javax.swing.GroupLayout(P_CAL);
        P_CAL.setLayout(P_CALLayout);
        P_CALLayout.setHorizontalGroup(
            P_CALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_CALLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P_CALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P_CALLayout.setVerticalGroup(
            P_CALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_CALLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        P_PROC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amikbdg/tacal/res/icons8_process_24px.png"))); // NOI18N

        LB_PG.setText("Process : Standby");

        javax.swing.GroupLayout P_PROCLayout = new javax.swing.GroupLayout(P_PROC);
        P_PROC.setLayout(P_PROCLayout);
        P_PROCLayout.setHorizontalGroup(
            P_PROCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_PROCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P_PROCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(P_PROCLayout.createSequentialGroup()
                        .addComponent(LB_PG)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        P_PROCLayout.setVerticalGroup(
            P_PROCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_PROCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_PROCLayout.createSequentialGroup()
                .addComponent(LB_PG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PG, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        File.setText("File");

        BrowseMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amikbdg/tacal/res/icons8_csv_24px.png"))); // NOI18N
        BrowseMenu.setText("Browse");
        BrowseMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseMenuActionPerformed(evt);
            }
        });
        File.add(BrowseMenu);

        ResetMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amikbdg/tacal/res/icons8_refresh_24px.png"))); // NOI18N
        ResetMenu.setText("Reset");
        ResetMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetMenuActionPerformed(evt);
            }
        });
        File.add(ResetMenu);
        File.add(jSeparator1);

        ExitMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amikbdg/tacal/res/icons8_shutdown_24px_1.png"))); // NOI18N
        ExitMenu.setText("Exit");
        File.add(ExitMenu);

        MenuBar.add(File);

        About.setText("Tentang");

        AboutMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amikbdg/tacal/res/icons8_info_24px.png"))); // NOI18N
        AboutMenu.setText("Tentang Aplikasi");
        AboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutMenuActionPerformed(evt);
            }
        });
        About.add(AboutMenu);

        MenuBar.add(About);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(P_CSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(P_CAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(P_PROC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(P_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P_CSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P_CAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(P_PROC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutMenuActionPerformed
        new About().show();
    }//GEN-LAST:event_AboutMenuActionPerformed

    private void B_BROWSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BROWSEActionPerformed
        int returnVal = CSV_BROWSE.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = CSV_BROWSE.getSelectedFile();
        //try {
          // What to do with the file, e.g. display it in a TextArea
          TF_FN.setText(CSV_BROWSE.getSelectedFile().getAbsolutePath());
          /*  try {
                //TF_FN.read( new FileReader( file.getAbsolutePath() ), null );
                //}// catch (IOException ex) {
                // System.out.println("problem accessing file"+file.getAbsolutePath());
                //}
                CSVReader reader = new CSVReader(new FileReader(CSV_BROWSE.getSelectedFile().getAbsolutePath()));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }*/
          LB_PG.setText("Process : Getting Absolute Path");
          PG.setValue(25);
          try
          {
        BufferedReader buff = new BufferedReader(new FileReader(CSV_BROWSE.getSelectedFile()));
        int row = 0;
        String read;
        LB_PG.setText("Process : Importing CSV to Table");
          PG.setValue(75);
        while((read = buff.readLine())!=null)
        {
            String[] array = read.split(",\"");
            
             for(int i = 0;i<array.length;i++)
             {
                 
                array[i] = array[i].replaceAll("\"", "");
             }
            dtm.addRow(new Object[0]);
            dtm.setValueAt(array[0], row, 0);
            dtm.setValueAt(array[1], row, 1);
            dtm.setValueAt(array[2], row, 2);
            dtm.setValueAt(array[3], row, 3);
            dtm.setValueAt(array[4], row, 4);
            System.out.println(array[0] + array[1] + array[2] + array[3] + array[4]);
            row++;
        }
        buff.close();
        dtm.removeRow(0);
        LB_PG.setText("Complete : Import Success");
          PG.setValue(100);
          }
          catch(IOException e)
          {
              LB_PG.setText("Error : Import CSV Gagal");
              PG.setValue(100);
          }
        
    } else {
        LB_PG.setText("Cancel : Ditolak User");
        PG.setValue(100);
    }
    }//GEN-LAST:event_B_BROWSEActionPerformed

    private void B_CALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CALActionPerformed
        // TODO add your handling code here:
        
        String S_tugas= (String) this.CB_PT.getSelectedItem();
        String S_uts= (String) this.CB_PUT.getSelectedItem();
        String S_uas= (String) this.CB_PUA.getSelectedItem();
        int N_tugas = Integer.parseInt(S_tugas);
        int N_uts = Integer.parseInt(S_uts);
        int N_uas = Integer.parseInt(S_uas);
        int tot_verif = (N_tugas+N_uts+N_uas);
        LB_PG.setText("Process : Parsing and Calculating Data");
          PG.setValue(50);
        if(tot_verif == 100)
            
        {
            try
            {
                for(int row=0;row<t_nilai.getRowCount();row++)
                {
                String n_tugas_t = t_nilai.getValueAt(row, 2).toString();
                String n_uts_t = t_nilai.getValueAt(row, 3).toString();
                String n_uas_t = t_nilai.getValueAt(row, 4).toString();
                if(n_uas_t.length() < 1)
                {
                    n_uas_t = "0";
                }
                if(n_uts_t.length() < 1)
                {
                    n_uts_t = "0";
                }
                if(n_tugas_t.length() < 1)
                {
                    n_tugas_t = "0";
                }
                int i_n_tugas = Integer.parseInt(n_tugas_t);
                int i_n_uts = Integer.parseInt(n_uts_t);
                int i_n_uas = Integer.parseInt(n_uas_t);
                System.out.println(i_n_uas);
                NA=(i_n_tugas * N_tugas / 100)
                        +(i_n_uts* N_uts / 100)
                        +( i_n_uas *
                        N_uas/100);
                    if(NA>=80)
                    {
                        NAP="A";
                    }
                    else if(NA>=70 && NA<80)
                    {
                        NAP="B";
                    }
                    else if(NA>=60 && NA<70)
                    {
                        NAP="C";
                    }
                    else if(NA>=50 && NA<60)
                    {
                        NAP="D";
                    }
                    else if(NA<50)
                    {
                        NAP="E";
                    }
                    else if(i_n_uas==0)
                    {
                        NAP="E";
                    }
                    else
                    {
                        NAP="E!VAL";
                    }
                    t_nilai.setValueAt(NAP, row, 5);
                }
                LB_PG.setText("Complete : Calculation Complete");
          PG.setValue(100);
            }
            catch(NumberFormatException ex)
            {
                LB_PG.setText("Error : NumberFormatException");
          PG.setValue(100);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Persentase dibawah 100%", "Perhatian", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_B_CALActionPerformed

    private void BrowseMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseMenuActionPerformed
        int returnVal = CSV_BROWSE.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = CSV_BROWSE.getSelectedFile();
        //try {
          // What to do with the file, e.g. display it in a TextArea
          TF_FN.setText(CSV_BROWSE.getSelectedFile().getAbsolutePath());
          /*  try {
                //TF_FN.read( new FileReader( file.getAbsolutePath() ), null );
                //}// catch (IOException ex) {
                // System.out.println("problem accessing file"+file.getAbsolutePath());
                //}
                CSVReader reader = new CSVReader(new FileReader(CSV_BROWSE.getSelectedFile().getAbsolutePath()));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }*/
          try
          {
        BufferedReader buff = new BufferedReader(new FileReader(CSV_BROWSE.getSelectedFile()));
        int row = 0;
        String read;
        while((read = buff.readLine())!=null)
        {
            String[] array = read.split(",\"");
            
             for(int i = 0;i<array.length;i++)
             {
                 
                array[i] = array[i].replaceAll("\"", "");
             }
            dtm.addRow(new Object[0]);
            dtm.setValueAt(array[0], row, 0);
            dtm.setValueAt(array[1], row, 1);
            dtm.setValueAt(array[2], row, 2);
            dtm.setValueAt(array[3], row, 3);
            dtm.setValueAt(array[4], row, 4);
            System.out.println(array[0] + array[1] + array[2] + array[3] + array[4]);
            row++;
        }
        buff.close();
        dtm.removeRow(0);
          }
          catch(IOException e)
          {
              LB_PG.setText("Error : Import CSV Gagal");
          }
        
    } else {
        LB_PG.setText("Cancel : Ditolak User");
    }
    }//GEN-LAST:event_BrowseMenuActionPerformed

    private void ResetMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetMenuActionPerformed
        new Main().show();
        this.dispose();
    }//GEN-LAST:event_ResetMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu About;
    private javax.swing.JMenuItem AboutMenu;
    private javax.swing.JButton B_BROWSE;
    private javax.swing.JButton B_CAL;
    private javax.swing.JButton B_EXPORT;
    private javax.swing.JButton B_Statistik;
    private javax.swing.JMenuItem BrowseMenu;
    private javax.swing.JComboBox<String> CB_PT;
    private javax.swing.JComboBox<String> CB_PUA;
    private javax.swing.JComboBox<String> CB_PUT;
    private javax.swing.JFileChooser CSV_BROWSE;
    private javax.swing.JMenuItem ExitMenu;
    private javax.swing.JMenu File;
    private javax.swing.JLabel LB_PG;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JProgressBar PG;
    private javax.swing.JPanel P_CAL;
    private javax.swing.JPanel P_CSV;
    private javax.swing.JPanel P_PROC;
    private javax.swing.JPanel P_Title;
    private javax.swing.JMenuItem ResetMenu;
    private javax.swing.JTextField TF_FN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable t_nilai;
    // End of variables declaration//GEN-END:variables
}
